export { default as Logo } from './Logo'
export { default as BookStackSVG } from './BookStackSVG'
export { default as BuildingSVG } from './BuildingSVG'
export { default as DocumentsSVG } from './DocumentsSVG'
export { default as HamMenuSVG } from './HamMenuSVG'
export { default as OpenBookSVG } from './OpenBookSVG'
