import type { Metadata } from 'next'
import localFont from "next/font/local"
import './globals.css'
import Provider from '@/providers/Provider'

const poppins = localFont({
  src: [
    {
      path: '../assets/fonts/poppins-v20-latin-regular.woff2',
      weight: '400',
      style: "normal"
    },
    {
      path: '../assets/fonts/poppins-v20-latin-700.woff2',
      weight: '700',
      style: "normal"
    }
  ],
  display: 'swap',
  variable: "--Poppins"
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Provider attribute="class" defaultTheme="dark" enableSystem storageKey='arms-theme'>
          {children}
        </Provider>
      </body>
    </html>
  )
}
