export { default as LandingVector } from './LandingVector.svg'
export { default as PeopleVector } from './PeopleVector.svg'
export { default as UploadVector } from './UploadVector.svg'
export { default as SignupVector } from './SignupVector.svg'
export { default as NewInstituteVector } from './NewInstituteVector.svg'